/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 d20.glb --transform
Files: d20.glb [552.13KB] > C:\code\portfolio\infinite-dungeon\public\models\d20-transformed.glb [67.41KB] (88%)
*/
import { useGLTF } from '@react-three/drei'

// face id lookup table -- specific to this model only!
const FACE_ID_LOOKUP = {
  1063: 1,
  154: 2,
  744: 3,
  174: 4,
  695: 5,
  278: 6,
  926: 7,
  210: 8,
  635: 9,
  408: 10,
  623: 11,
  419: 12,
  796: 13,
  119: 14,
  775: 15,
  291: 16,
  755: 17,
  244: 18,
  900: 19,
  0: 20
}

const FILE_PXLMESH_LOGO = './models/d20-compressed.glb'

useGLTF.preload(FILE_PXLMESH_LOGO)

const D20 = (props) => {
  const { nodes, materials } = useGLTF(FILE_PXLMESH_LOGO)

  return (
    <group {...props} ref={props.child_ref}>
      <mesh
        castShadow={props.castShadow}
        geometry={nodes.d20_red_plastic.geometry}
        material={materials['red plastic']}
      />
    </group>
  )
}

export { FACE_ID_LOOKUP }
export default D20